# Generated by Django 3.2.5 on 2021-07-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maqolalar', '0003_maqola_maqolalar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maqolalar',
        ),
    ]
