# Generated by Django 3.2.5 on 2021-07-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqolalar', '0004_delete_maqolalar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maqolalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=1500)),
                ('text', models.TextField()),
            ],
        ),
    ]
